# Generated by Django 5.0.4 on 2024-05-31 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=45)),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tabla_Cliente',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=90)),
                ('unidades', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'tabla_Producto',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numeroF', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cliente')),
            ],
            options={
                'db_table': 'tabla_Factura',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cliente')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.producto')),
            ],
            options={
                'db_table': 'tabla_Venta',
            },
        ),
    ]
