# Generated by Django 5.0.4 on 2024-05-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='apeliidos',
            new_name='apellidos',
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='tabla_clientes',
        ),
    ]
