# Generated by Django 5.0.4 on 2024-05-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_apeliidos_clientes_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=45),
        ),
    ]
