# Generated by Django 5.0.4 on 2024-05-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_forma_pago_factura_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numeroF',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
