# Generated by Django 5.0.4 on 2024-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_clientes_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
