# Generated by Django 5.0.4 on 2024-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_clientes_cedula_alter_clientes_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
