# Generated by Django 5.0.4 on 2024-06-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_factura_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
