# Generated by Django 5.0.4 on 2024-05-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_inventario_precios_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=100)),
                ('unidades', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'tabla_Productos',
            },
        ),
        migrations.AlterField(
            model_name='ventas',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productos'),
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
