# Generated by Django 5.0.4 on 2024-05-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_productos_alter_ventas_articulo_delete_precios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precio',
        ),
    ]
