# Generated by Django 5.0.4 on 2024-05-16 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.productos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tabla_Precios',
            },
        ),
    ]
