# Generated by Django 5.0.4 on 2024-05-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_ventas_articulo_remove_ventas_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.productos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tabla_Precios',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientes')),
            ],
            options={
                'db_table': 'tabla_Ventas',
            },
        ),
    ]
