# Generated by Django 5.0.4 on 2024-05-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_precios_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apps.productos'),
        ),
    ]
