# Generated by Django 5.0.4 on 2024-05-16 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_precios_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='precios',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productos'),
        ),
    ]
