# Generated by Django 5.0.4 on 2024-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_precios_id_alter_precios_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='nombre_articulo',
            field=models.CharField(max_length=90),
        ),
    ]
