# Generated by Django 5.0.4 on 2024-07-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_venta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='porcentaje',
            field=models.CharField(default=15, max_length=2),
            preserve_default=False,
        ),
    ]
