# Generated by Django 5.0.4 on 2024-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_factura_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
