# Generated by Django 5.0.4 on 2024-05-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_productos_nombre_articulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precios',
            new_name='Precio',
        ),
        migrations.AlterModelTable(
            name='precio',
            table='tabla_Precio',
        ),
    ]
