# Generated by Django 5.0.4 on 2024-07-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_factura_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='porcentaje',
            field=models.IntegerField(),
        ),
    ]
