# Generated by Django 5.0.4 on 2024-05-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_rename_precios_precio_alter_precio_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precio',
            new_name='Precios',
        ),
        migrations.AlterModelTable(
            name='precios',
            table='tabla_Precios',
        ),
    ]
