# Generated by Django 5.0.4 on 2024-05-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
